import Sidebar from "@/components/sidebar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="container">
          <div className="sidebar">
            <Sidebar />
          </div>
          <div className="content">{children}</div>
        </div>
      </body>
    </html>
  );
}
